// Supabase
export const SUPABASE_KEY = process.env.SUPABASE_KEY;
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_INSTALLATION_ACCESS_TOKENS_TABLE =
  process.env.SUPABASE_INSTALLATION_ACCESS_TOKENS_TABLE || 'installation_access_tokens';
export const SUPABASE_INSTALLATION_ACCESS_TOKENS_URL = `${SUPABASE_URL}/rest/v1/${SUPABASE_INSTALLATION_ACCESS_TOKENS_TABLE}`;
